apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: gce-persistent-volume
    fsType: ext4