apiVersion: v1
kind: Pod
metadata:
  name: gce-persistent-volume-pod
  labels:
    env: volume-test
spec:
  containers:
    - image: mongo
      name: gce-persistent-volume-mongo
      volumeMounts:
        - name: gce-persistent-disk-volume
          mountPath: /data/db
  volumes:
    - name: gce-persistent-disk-volume
      persistentVolumeClaim:
        claimName: gce-pvc