apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-storage-class
provisioner: kubernetes.io/gce-pd # gce 프로비저닝을 위한 플러그인
parameters:
  type: pd-standard
  fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true # This feature when set to true, allows the users to resize the volume by editing the corresponding PVC object.
volumeBindingMode: Immediate # default